USE rcu ;
BEGIN;

UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 449;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 450;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 548;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 549;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 550;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 610;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 649;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 650;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 710;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 749;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 750;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 810;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 849;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 850;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 948;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 949;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 950;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 1048;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 1049;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 1050;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2132;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2133;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2134;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2135;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2136;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2137;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2138;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2139;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2140;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2141;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2142;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2143;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2144;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2145;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2146;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2147;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2148;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2149;
UPDATE `rcu_room_state` SET if_have = 0 WHERE room_id = 2150;

COMMIT;